services:
  client_service:
    build:
      context: ./client_service
      dockerfile: DFILE
    ports:
      - "8080:8080"
    environment:
      - DART_ENV=production
    volumes:
      - ./client_service:/app/src
    networks:
      - gis_network

networks:
  gis_network:
    driver: bridge