version: '3.8'

services:
  # Database Service
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 133133
      POSTGRES_DB: gis
    volumes:
      - ./Gis_create.sql:/docker-entrypoint-initdb.d/Gis_create.sql
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - gis-network

  # Micro Transport Microservice
  transport_micros_service:
    build:
      context: ./gis_microservicios/Transport_micros_service
      dockerfile: Dockerfile
    container_name: transport_micros_service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=133133
    networks:
      - gis-network

# Shared network for all services
networks:
  gis-network:
    driver: bridge

