name: client_service
description: Client registration microservice for GIS La Paz
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  postgres: ^2.6.1
  dart_jsonwebtoken: ^2.8.0
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  http: ^1.1.0